Properties = {
    'AGE' : [
                [	'10s'	,	'20대 초반'	,	0.1	]	,
                [	'70s'	,	'30대 후반'	,	0.5	]   ,
                [	'60s'	,	'30대 중반'	,	0.5	]	,
                [	'50s'	,	'30대 초반'	,	0.5	]	,
                [	'40s'	,	'20대 후반'	,	5	]	,
                [	'30s'	,	'20대 중반'	,	6	]	,
                [	'20s'	,	'20대 초반'	,	7	]	
                ],

    'MURDER TOOL' : [
                    [	'Black Tea'	,	'홍차'	,	2	]	,
                    [	'Guillotine Paper Cutter'	,	'오래되어 녹슬고 날이 무뎌진 작두'	,	12	]	,
                    [	'Cattle Gun'	,	'도축용 에어 건'	,	13	]	,
                    [	'Prosthetic Hand'	,	'의수'	,	14	]	,
                    [	'Prosthetic Leg'	,	'의족'	,	15	]	,
                    [	'Code Of Law'	,	'<민법강의> 책 양장본'	,	16	]	,
                    [	'Sharp Pencil'	,	'날카롭게 갈린 연필'	,	17	]	,
                    [	'Bass Guitar'	,	'4kg는 되어 보이는 무거운 베이스 기타'	,	18	]	,
                    [	'Colt Python '	,	'나무 손잡이의 콜트 파이슨 권총'	,	19	]	,
                    [	'Collectible Suseok'	,	'나무 바닥 장식이 달린 수집용 수석'	,	20	]	,
                    [	'VX Spray'	,	'VX 스프레이'	,	21	]	,
                    [	'Pure Nicotine'	,	'니코틴 원액'	,	22	]	,
                    [	'Poisonous Mushroom Broth'	,	'붉은사슴뿔버섯을 달인 물'	,	23	]	,
                    [	'Cocaine'	,	'코카인'	,	122	]	,
                    [	'Heroine'	,	'헤로인'	,	123	]	,
                    [	'Poisoned Cool-Aid '	,	'냄새가 이상한 레몬에이드'	,	124	]	,
                    [	'Stainless Sashimi Knife'	,	'단조 스텐 사시미칼'	,	24	]	,
                    [	'Katana'	,	'장식용 일본도'	,	25	]	,
                    [	'Rusty Sickle'	,	'녹슨 나무 손잡이 낫'	,	26	]	,
                    [	'Vintage Straight Razor'	,	'날이 잘 벼려진 구식 면도칼'	,	27	]	,
                    [	'Ivory Bowie Knife'	,	'상아로 만든 손잡이가 달린 수집용 보위 나이프'	,	28	]	,
                    [	'Machete '	,	'길이 35cm 정도 되는 마체테'	,	29	]	,
                    [	'Collectible Folding Knife'	,	'수집용 폴딩 나이프'	,	30	]	,
                    [	'WASP Injection Knife'	,	'압축 가스가 내장된 발리스틱 나이프'	,	31	]	,
                    [	'Disposable Syringe'	,	'의료용 일회용 주사기'	,	32	]	,
                    [	'Fire Axe'	,	'빨간색 소방용 도끼'	,	33	]	,
                    [	'Black Handled Scissors'	,	'검은색 손잡이의 주방용 가위'	,	34	]	,
                    [	'Fabric Scissors '	,	'원단 재단용 가위'	,	35	]	,
                    [	'Broken Soju Bottle'	,	'꺠진 330ML 초록색 소주병'	,	36	]	,
                    [	'Soju Bottle'	,	'깨지지 않은 330ML 초록색 소주병'	,	37	]	,
                    [	'Transparent Vodka Bottle'	,	'투명한 500ML 보드카 병'	,	38	]	,
                    [	'Sealed Wine Bottle'	,	'와인이 들어 있는 750ml 와인 병 '	,	39	]	,
                    [	'Coca-cola Bottle'	,	'350ml 코카콜라 병'	,	40	]	,
                    [	'Crosshead Screwdriver'	,	'노란색 플라스틱 손잡이가 달린 십자 드라이버'	,	41	]	,
                    [	'Iron Coping Saw'	,	'쇠 손잡이의 무거운 줄톱'	,	42	]	,
                    [	'Wire Saw'	,	'실처럼 얇은 와이어 톱'	,	43	]	,
                    [	'Blue Plastic Nipper'	,	'파란색 손잡이가 달린 니퍼'	,	44	]	,
                    [	'Cordless Drill'	,	'나무용 비트가 장착된 B 사의 전동 드릴 '	,	45	]	,
                    [	'Old Circular Saw'	,	'여러 번 사용한 듯한 낡은 원형 톱'	,	46	]	,
                    [	'Quick Pipe Wrench'	,	'파란색 손잡이의 퀵 파이프 렌치'	,	47	]	,
                    [	'Chisel '	,	'조각 작업용 정'	,	48	]	,
                    [	'Ice Pick'	,	'나무 손잡이가 달린 얼음 송곳'	,	49	]	,
                    [	'Duct Tape'	,	'청테이프'	,	50	]	,
                    [	'Studded Dirty Knuckle'	,	'마디에 스터드가 박힌 두껍고 더러운 금색 너클'	,	51	]	,
                    [	'Wooden Crutch'	,	'목발'	,	52	]	,
                    [	'Aluminum Baseball Bat'	,	'알루미늄 재질의 주황색 야구 배트'	,	53	]	,
                    [	'Board With Nails'	,	'못이 박혀 있는 각목'	,	54	]	,
                    [	'Heavy Glass Ashtray'	,	'화려하게 장식된 무거운 유리 재떨이'	,	55	]	,
                    [	'Metal Pipe'	,	'70cm 정도 되는 쇠 파이프'	,	56	]	,
                    [	'Shinai'	,	'연습용 죽도 '	,	57	]	,
                    [	'Police Nightstick'	,	'검은색 경찰 곤봉'	,	58	]	,
                    [	'Expandable Nightstick'	,	'검은색 호신용 삼단 곤봉'	,	59	]	,
                    [	'Fishing Wire'	,	'낚싯줄'	,	60	]	,
                    [	'Piano Wire'	,	'피아노줄'	,	61	]	,
                    [	'Jute Twine'	,	'갈색 노끈'	,	62	]	,
                    [	'Packing Strap'	,	'포장용 빨간색 비닐끈'	,	63	]	,
                    [	'Striped Tie'	,	'파란색 줄무늬 넥타이'	,	64	]	,
                    [	'Climbing Rope'	,	'등반용 자일'	,	65	]	,
                    [	'White Silk Curtain'	,	'하얀색 실크 커튼'	,	66	]	,
                    [	'Thick Rubber Wire'	,	'검은색 두꺼운 전선'	,	67	]	,
                    [	'Computer Monitor'	,	'S사의 26인치 컴퓨터 모니터'	,	68	]	,
                    [	'Ski Pole'	,	'스키 폴'	,	70	]	,
                    [	'BBQ Fork'	,	'바베큐 포크'	,	71	]	,
                    [	'Dental Drill'	,	'굵은 비트가 박혀 있는 치과용 드릴 '	,	72	]	,
                    [	'Porcelain Pot'	,	'선인장이 심어진 9kg 도자기 화분'	,	73	]	,
                    [	'Teracotta Pot'	,	'흙으로 꽉 찬 7kg 토분'	,	74	]	,
                    [	'Mechanical Pencil'	,	'쇠로 만들어진 제도용 샤프 펜슬'	,	75	]	,
                    [	'Female Stocking'	,	'여성용 커피색 스타킹'	,	76	]	,
                    [	'Gasoline With Zippo'	,	'휘발유와 지포 라이터 '	,	77	]	,
                    [	'Machine Gun K15'	,	'기관총 K15'	,	78	]	,
                    [	'Microgun XM214'	,	'XM214 마이크로건'	,	79	]	,
                    [	'Sniper Gun ULR338'	,	'저격소총 ULR 338'	,	80	]	,
                    [	'Walther PPK .32ACP'	,	'장식용 32구경 PPK 독일제'	,	81	]	,
                    [	'Bereta APX'	,	'권총 베레타 APX'	,	82	]	,
                    [	'Remington M7188'	,	'산탄총 레밍턴 M7188'	,	83	]	,
                    [	'Sharp Edged Stone'	,	'1kg 정도의 뾰족한 돌'	,	84	]	,
                    [	'Round Edged Stone'	,	'2kg 정도 되는 둥근 돌'	,	85	]	,
                    [	'Wood Branch'	,	'길이 1m의 나뭇가지'	,	86	]	,
                    [	'Wooden Cane'	,	'원목으로 만들어진 나무 지팡이'	,	87	]	,
                    [	'Venomous Snake Cage'	,	'독사가 든 케이지'	,	88	]	,
                    [	'Water'	,	'물'	,	89	]	,
                    [	'Sulfuric Acid'	,	'황산'	,	90	]	,
                    [	'Mercury'	,	'수은'	,	91	]	,
                    [	'Pottassium Chloride'	,	'염화칼륨'	,	92	]	,
                    [	'Bottle of Propofol'	,	'프로포폴 약병'	,	93	]	,
                    [	'Potassium Cyanide'	,	'청산가리'	,	94	]	,
                    [	'Wrapped Blowfish Sashimi'	,	'포장된 복어회'	,	95	]	,
                    [	'Glacial Acetic Acid'	,	'종이컵에 가득 담긴 빙초산'	,	96	]	,
                    [	'Poisoned Medicine'	,	'부자탕 한약'	,	97	]	,
                    [	'Muscaria Mushroom'	,	'무스카리아 독버섯'	,	98	]	,
                    [	'Green Paring Knife'	,	'연두색 손잡이가 달린 과도'	,	99	]	,
                    [	'Wooden Handle Cleaver'	,	'나무 손잡이가 달린 중식도'	,	100	]	,
                    [	'Rusty Pickaxe '	,	'녹슬고 손때가 탄 곡괭이'	,	101	]	,
                    [	'Surgical Blade'	,	'날카로운 의료용 메스'	,	102	]	,
                    [	'Wooden Handle Hatchet'	,	'나무 손잡이가 달린 캠핑용 도끼'	,	103	]	,
                    [	'Broken Beer Bottle'	,	'깨진 500ML 갈색 맥주병'	,	104	]	,
                    [	'Rusty Hammer'	,	'검은색 고무 손잡이가 달린 녹슨 쇠 망치'	,	105	]	,
                    [	'Stained Handsaw'	,	'짙은 갈색의 얼룩이 묻어 있는 나무 손잡이 쇠톱'	,	106	]	,
                    [	'Red Chainsaw'	,	'붉은색 손잡이의 큰 전기톱'	,	107	]	,
                    [	'Wodden Handle Shovel'	,	'손때 묻은 나무 손잡이 삽'	,	108	]	,
                    [	'Pry Bar'	,	'쇠 지렛대'	,	109	]	,
                    [	'Golf Club'	,	'4번 아이언 골프 클럽'	,	111	]	,
                    [	'Sport Towel '	,	'파란색 스포츠 수건'	,	112	]	,
                    [	'Charging Cable'	,	'검은색 충전기 케이블'	,	113	]	,
                    [	'Fire Poker '	,	'벽난로용 불쏘시개'	,	114	]	,
                    [	'Walther PPK  '	,	'검은색 발터 PPK 권총'	,	116	]	,
                    [	'Desert Eagle '	,	'소음기가 달린 데저트 이글 권총'	,	117	]	,
                    [	'Submachine Gun AR-18'	,	'기관단총 AR-18'	,	118	]	,
                    [	'Irregular Shaped Rock'	,	'모양이 일정치 않은 10kg 정도의 바위'	,	119	]	,
                    [	'Hydrochloric Acid'	,	'염산'	,	120	]	,
                    [	'Tetrodotoxin Powder'	,	'테트로도톡신 가루'	,	121	]	,
                    [	'Wrapped Knife'	,	'신문지로 싼 식칼'	,	125	]	,
                    [	'Yellow Box Cutter'	,	'노란색 공업용 커터칼'	,	126	]	,
                    [	'Green Utility Knife'	,	'초록색 문구용 커터칼'	,	127	]	,
                    [	'Beer Bottle'	,	'깨지지 않은 500ml 갈색 맥주병'	,	128	]	,
                    [	'Flathead Screwdriver'	,	'고무 손잡이가 달린 일자 드라이버'	,	129	]	,
                    [	'Monkey Wrench '	,	'빨간색 12인치 몽키 스패너'	,	130	]	,
                    [	'Wooden Baseball Bat'	,	'밝은 갈색의 나무 야구 배트'	,	131	]	,
                    [	'Black Belt '	,	'남성용 검정색 벨트'	,	132	]	,
                    [	'Rusty Shotgun'	,	'청테이프가 감긴 녹슨 샷건'	,	134	]	,
                    [	'Submachine Gun K16'	,	'기관단총 K16'	,	135	]	,
                    [	'Pesticide'	,	'페트병에 담겨 있는 농약'	,	136	],
                    [	'Red Brick'	,	'붉은색 벽돌'	,	133	]	,
                    [	'Wooden Board'	,	'공사장에서 사용하는 각목'	,	110	],
                    ],

    'CLOTHE - T' :  [
                    [	'Shirtless'	,	'아무것도 입지 않은 맨몸'	,	1	]	,
                    [	'Black Poncho Raincoat'	,	'검은색 판초 우의'	,	2	]	,
                    [	'Old Leather Jacket'	,	'아주 오래되어 낡은 검은색 가죽 라이더 자켓'	,	3	]	,
                    [	'Luxury Trench Coat'	,	'명품 브랜드의 검은색 트렌치 코트 '	,	4	]	,
                    [	'Black Tshirt'	,	'검은색 무지 반팔'	,	5	]	,
                    [	'Bulletproof Vest'	,	'방탄 조끼'	,	32	]	,              
                    [	'White Tshirt'	,	'흰색 무지 반팔'	,	7	]	,
                    [	'Khaki Tshirt'	,	'카키색 무지 맨투맨'	,	8	]	,
                    [	'Logo Printed Sweatshirt'	,	'유명 브랜드 로고가 프린트되어 있는 회색 맨투맨'	,	9	]	,
                    [	'Varsity Jacket'	,	'대학교와 학과 이름, 학번과 기수가 수놓인 자켓 '	,	10	]	,
                    [	'Charcoal Hoodie'	,	'어두운 회색 후드 티셔츠'	,	11	]	,
                    [	'Stripe Turtleneck Knit'	,	'검은색/흰색 스트라이프 폴라 니트 '	,	12	]	,
                    [	'White Shirt'	,	'흰색 와이셔츠와 붉은색 넥타이 '	,	13	]	,
                    [	'Stripe Tshirt '	,	'푸른색/흰색 스트라이프 반팔 셔츠 '	,	14	]	,
                    [	'Black Hiking Jacket'	,	'검은색/회색 배색 등산복 상의'	,	15	]	,
                    [	'Green Hiking Jacket'	,	'연두색/회색 배색 등산복 상의'	,	16	]	,
                    [	'China Collar Shirt'	,	'땀으로 젖어 있었던 차이나 칼라 와이셔츠'	,	17	]	,
                    [	'Lace Blouse'	,	'가슴 부분에 프릴이 달린 블라우스'	,	18	]	,
                    [	'Emerald Coach Jacket'	,	'어두운 초록색의 코치 자켓 '	,	19	]	,
                    [	'Duck Patch Hoodie'	,	'소매에 노란색 오리 패치가 박힌 후드집업'	,	20	]	,
                    [	'Pilot Bomber Jacket'	,	'비닐 재질의 남색 항공 점퍼 '	,	21	]	,
                    [	'Logo Printed Windbreaker'	,	'유명 브랜드 로고가 있는 바람막이 점퍼 '	,	22	]	,
                    [	'Short Padded Coat'	,	'허리 기장의 흰색 숏 패딩 점퍼 '	,	23	]	,
                    [	'Old Denim Jacket'	,	'오래되어 낡은 명품 브랜드의 청자켓 '	,	24	]	,
                    [	'Luxury Brown Shearing'	,	'명품 브랜드의 옅은 갈색 무스탕 '	,	25	]	,
                    [	'Yellow Short Cardigan'	,	'노란색 짧은 니트 가디건'	,	26	]	,
                    [	'Purple Short Cardigan'	,	'짙은 보라색의 짧은 니트 가디건'	,	27	]	,
                    [	'Long buttonless Cardigan'	,	'갈색의 단추 없는 긴 가디건'	,	28	]	,
                    [	'Crop Vest Knit'	,	'옆부분에 트임이 있는 크롭 기장의 초록색 조끼'	,	29	]	,
                    [	'Long Sleeve Tshirt'	,	'소매가 매우 긴 기장의 청록색 티셔츠'	,	30	]	,
                    [	'Ivy League Hoodie'	,	'해외 대학교 로고와 이름이 수놓아진 붉은색 후드 티셔츠'	,	31	]	,
                    [	'Cotton Zip Hoodie'	,	'면 소재 트레이닝복 상의'	,	33	]	,
                    [	'Long Padded Coat'	,	'로고를 의도적으로 떼어낸 검은색 롱패딩'	,	34	]	,
                    [	'Undershirt'	,	'흰색 런닝 셔츠'	,	35	]	,
                    [	'Brown Wool Coat'	,	'짙은 갈색의 울 코트'	,	36	]	,
                    [	'Grey Knit Shirt'	,	'카라가 있는 연한 회색 니트 셔츠'	,	37	]	,
                    [	'Printed White Tshirt'	,	'해변 사진이 나염되어 있는 흰색 반팔'	,	38	]	,
                    [	'Blue Shirt'	,	'파란색 와이셔츠와 검은색 넥타이'	,	39	]	,
                    [	'Grey Hiking Jacket'	,	'회색/분홍색 배색 등산복 상의 '	,	40	]	,
                    [	'Grey Fleece Hoodie'	,	'밝은 회색의 기모 후드집업'	,	41	]	,
                    [	'Long Field Jacket'	,	'무릎 기장의 카키색 야상 점퍼 '	,	42	]	,
                    [	'Vest With Slits'	,	'옆부분에 트임이 있는 긴 흰색 니트 조끼'	,	43	]	,
                    [	'Jersey Zip Hoodie'	,	'저지 소재 트레이닝복 상의'	,	44	],
                    [	'Printed Black Tshirt'	,	'영어 문구가 쓰여져 있는 검은색 반팔'	,	6	]
                    ],
    'CLOTHE - B' :  [
                    [	'Stained Blue Jeans'	,	'알 수 없는 얼룩이 져 있는 짙은 청색 청바지 '	,	1	],
                    [	'Cotton Shorts'	,	'면 소재의 트레이닝 반바지 '	,	2	]	,
                    [	'Black Stitched Denim'	,	'검은색 스티치 데님 바지 '	,	3	]	,
                    [	'Naked'	,	'아무것도 입지 않은 하체'	,	4	]	,
                    [	'Slit Bootcut Jeans'	,	'트임이 있는 부츠컷 청바지 '	,	5	]	,
                    [	'Wide Denim Pants'	,	'흰색 와이드 데님 팬츠 '	,	6	]	,
                    [	'Jersey Athletic Pants'	,	'저지 소재 트레이닝복 하의 '	,	7	]	,
                    [	'Semi Wide Pants'	,	'얇은 소재의 세미 와이드 바지'	,	8	]	,
                    [	'White Jogger Pants'	,	'흰색 두꺼운 조거 팬츠'	,	9	]	,
                    [	'Grey Jogger Pants'	,	'회색 두꺼운 조거 팬츠'	,	10	]	,
                    [	'Grey Hiking Pants'	,	'회색/분홍색 배색 등산복 하의'	,	11	]	,
                    [	'Gren Hiking Pants'	,	'연두색/회색 배색 등산복 하의'	,	12	]	,
                    [	'Wide Cargo Pants'	,	'카키색 와이드 카고 바지 '	,	13	]	,
                    [	'Charcoal Tucked Trousers'	,	'핀턱이 있는 차콜 컬러 긴 바지 '	,	14	]	,
                    [	'Luxury Athletic Pants'	,	'유명 브랜드의 트레이닝복 하의 '	,	15	]	,
                    [	'Cropped Linin Trousers'	,	'밝은 갈색의 9부 린넨 바지 '	,	16	]	,
                    [	'Black Leggings'	,	'검은색 레깅스'	,	17	]	,
                    [	'Cargo Jogger Slacks'	,	'검은색 카고 조거 슬랙스 팬츠 '	,	18	]	,
                    [	'Destroyed Jeans'	,	'옅은 청색의 찢어진 청바지 '	,	19	]	,
                    [	'Plain Denim Jeans'	,	'워싱이나 스크래치가 없는 옅은 청색의 데님 바지'	,	20	]	,
                    [	'Stained Skinny Jean'	,	'검은색 무늬 있는 스키니 진'	,	21	]	,
                    [	'Maxi Knit Skirt'	,	'검은색 맥시 니트 스커트 '	,	22	]	,
                    [	'Washed Grey Jeans'	,	'밝은 회색의 워싱이 많이 된 청바지 '	,	23	]	,
                    [	'Leather Biker Jeans'	,	'두꺼운 바이커 가죽 바지 '	,	24	]	,
                    [	'White Painted Dnim'	,	'흰색 페인트 그림이 한 쪽에 그려진 블랙 데님 바지 '	,	25	]	,
                    [	'Suit Trousers'	,	'검은색 정장 바지'	,	26	]	,
                    [	'Underwear'	,	'사각형 트렁크 팬티 '	,	27	]	,
                    [	'Black Hiking Pants'	,	'검은색/회색 배색 등산복 하의'	,	28	]	,
                    [	'Skinny Jean '	,	'진청 스키니 진 '	,	29	]	,
                    [	'Cotton Athletic Pants'	,	'면 소재 트레이닝복 하의'	,	30	]	,
                    [	'Linen Wide Pants'	,	'린넨 소재 와이드 팬츠'	,	31	]	,
                    [	'Shorts With Leggings'	,	'반바지와 검은색 레깅스'	,	32	]	,
                    [	'Fleece Pajama Pants'	,	'남색/흰색 체크무늬 수면 바지'	,	33	]	,
                    [	'Black Slacks'	,	'검은색 슬랙스 '	,	34	]

    ],

    'SHOES' :       [
                    [	'Wellies'	,	'종아리 중간까지 오는 고무 장화'	,	1	]	,
                    [	'Black Chelsea Boots'	,	'검은색 첼시 부츠 '	,	3	]	,
                    [	'Old Leather Oxford'	,	'오래된 갈색 가죽 옥스포드 '	,	4	]	,
                    [	'Skyblue Flip Flop'	,	'하늘색 쪼리'	,	5	]	,
                    [	'Brown Flip Flop'	,	'갈색 스팽글 장식 플립플랍'	,	6	]	,
                    [	'Logo Printed Slider'	,	'유명 브랜드 로고가 있는 슬리퍼 '	,	7	]	,
                    [	'Black Dress Shoes'	,	'검은색 유광 정장 구두 '	,	8	]	,
                    [	'White Stained Boots'	,	'흰색의 얼룩진 8홀 가죽 워커'	,	9	]	,
                    [	'Cherry Colored Boots'	,	'짙은 체리색 6홀 가죽 워커'	,	10	]	,
                    [	'Blue Colored Boots'	,	'짙은 남색 6홀 가죽 워커'	,	11	]	,
                    [	'Black Boots'	,	'검은색 8홀 가죽 워커'	,	12	]	,
                    [	'Black Long Boots'	,	'검은색 10홀 가죽 워커 '	,	13	]	,
                    [	'Knee High Wellies'	,	'무릎까지 오는 고무 장화'	,	14	]	,
                    [	'Thigh High Wellies'	,	'허벅지까지 오는 고무 장화'	,	15	]	,
                    [	'Brown Leather Loafer'	,	'연갈색 무광 가죽 로퍼'	,	16	]	,
                    [	'Black Leather Loafer'	,	'검은색 무광 가죽 로퍼 '	,	17	]	,
                    [	'Ivowy Suede Moccasin'	,	'아이보리색 스웨이드 모카신'	,	18	]	,
                    [	'Suede Boat shoes'	,	'갈색 스웨이드 보트슈즈'	,	19	]	,
                    [	'Ochre Leather Loper'	,	'황토색 가죽 로퍼'	,	20	]	,
                    [	'Bare Foot'	,	'맨발'	,	21	]	,
                    [	'Red Converse '	,	'빨간색 컨버스 운동화'	,	22	]	,
                    [	'Ivory Converse'	,	'아이보리색 컨버스 운동화'	,	23	]	,
                    [	'Blue Football Boots'	,	'파란색/노란색 배색 축구화'	,	24	]	,
                    [	'Red Football Boots'	,	'빨간색/검은색 배색 축구화'	,	25	]	,
                    [	'Combat Boots'	,	'군화 '	,	2	]	,
                    [	'German Army Trainers'	,	'갈색 고무 밑창의 흰색 독일군 스니커즈 '	,	26	]	,
                    [	'Chess Patteren loafer'	,	'체스판 무늬의 슬립온'	,	27	]	,
                    [	'White Running Shoes'	,	'하얀색/파란색 배색의 유명 브랜드 러닝화'	,	28	]	,
                    [	'White Basketball Shoes'	,	'흰색 농구화'	,	29	]	,
                    [	'Black Low Sneakers'	,	'검은색 낮은 운동화'	,	30	]	,
                    [	'Black Converse'	,	'검은색 컨버스 운동화'	,	31	]	,
                    [	'Strapped Leather Sandal'	,	'스트랩이 두 개 달려 있는 검정색 가죽 샌들'	,	32	]	,
                    [	'White Platform Sneakers'	,	'키높이 흰색 스니커즈 '	,	33	]
                    ],

    'HEADWEAR' :   [
                    [	'Matilda Bob'	,	'검은색 칼단발'	,	1	]	,
                    [	'Mid-long Hair'	,	'어깨선까지 오는 중단발'	,	2	]	,
                    [	'Bob Hair'	,	'단발'	,	3	]	,
                    [	'Long Black Hair'	,	'장발 검은 생머리 '	,	4	]	,
                    [	'Long Bleached hair'	,	'장발 탈색모'	,	5	]	,
                    [	'Long Blonde hair'	,	'장발 금발 머리 '	,	6	]	,
                    [	'Long Brown hair'	,	'장발 밝은 갈색 염색머리'	,	7	]	,
                    [	'Low Ponytail'	,	'장발 낮게 묶은 포니테일 '	,	8	]	,
                    [	'Long Curly Hair'	,	'장발 곱슬머리 '	,	9	]	,
                    [	'Long Layered Hair'	,	'장발 레이어드 컷 '	,	10	]	,
                    [	'Long Permed Hair'	,	'장발 파마머리 '	,	11	]	,
                    [	'Cherry Red Hair'	,	'체리 레드 염색머리 '	,	12	]	,
                    [	'Long Hippie Perm'	,	'장발 밝은 갈색 히피펌'	,	13	]	,
                    [	'Mid-long Ponytail'	,	'중단발 낮게 묶은 포니테일'	,	14	]	,
                    [	'Mid-long Straight Hair'	,	'중단발 검은 생머리 '	,	15	]	,
                    [	'Mid-long Curly Hair'	,	'중단발 밝은 갈색 곱슬머리 '	,	16	]	,
                    [	'Bob With Bangs'	,	'앞머리 있는 검은색 보브 컷'	,	17	]	,
                    [	'Perm With Bangs'	,	'앞머리 있는 갈색 파마 머리'	,	18	]	,
                    [	'Pixie Cut'	,	'앞머리 있는 단정한 숏컷'	,	19	]	,
                    [	'Short Curly Hair'	,	'굵은 파마를 한 옅은 갈색의 숏컷'	,	20	]	,
                    [	'Brown Short Babyperm'	,	'짙은 갈색의 짧은 베이비 펌 커트 머리'	,	21	]	,
                    [	'Black Short Babyperm'	,	'검은색의 짧은 베이비 펌 커트 머리'	,	22	]	,
                    [	'Two Block Haircut'	,	'왁스로 손질된 검은색 투블럭 머리'	,	23	]	,
                    [	'Natural Two Block'	,	'손질되지 않은 검은색 투블럭 머리'	,	24	]	,
                    [	'Pink Permed Hair'	,	'밝은 분홍색의 커트 파마 머리'	,	25	]	,
                    [	'Short Permed Hair'	,	'밝은 갈색의 쉐도우 펌 커트 머리'	,	26	]	,
                    [	'Bald Hair'	,	'대머리 '	,	27	]	,
                    [	'Side bangs'	,	'옆으로 넘긴 앞머리'	,	28	]	,
                    [	'Without Bangs'	,	'앞머리가 있는 머리'	,	29	]	,
                    [	'With Bangs'	,	'앞머리 있음'	,	31	]	,
                    [	'Buzz cut hair'	,	'반삭'	,	32	]	,
                    [	'With Hats'	,	'모자를 쓴 머리'	,	33	]	,
                    [	'Long Hair'	,	'어깨선을 넘는 장발'	,	34	]	,
                    [	'Short Hair'	,	'숏컷'	,	35	]	,
                    [	'High Ponytail'	,	'장발 높게 묶은 포니테일'	,	36	]	,
                    [	'Dandy Hairstyle'	,	'검은색 댄디 컷'	,	37	]	,
                    [	'Comma Hairstyle'	,	'검은색 쉼표 머리 '	,	38	]	,
                    [	'Pomade Hair'	,	'포마드 헤어 '	,	39	]
     ],

    'ACCESSORY' :   [
                    [	'Leon Sunglasses'	,	'레옹 선글라스'	,	1	]	,
                    [	'Thick Glasses'	,	'눈이 잘 보이지 않는 뿔테 안경 '	,	3	]	,
                    [	'Hand Prothetics'	,	'의수'	,	1	]	,
                    [	'Skull Shaped Ring'	,	'해골 모양으로 조각된 은색 반지'	,	4	]	,
                    [	'Hipsack With Cigarette'	,	'담배와 라이터가 든 힙색 가방'	,	27	]   ,
                    [	'Left Ear Pierced'	,	'왼쪽 귀에 1개 이상의 피어싱'	,	5	]	,
                    [	'Right Ear Pierced'	,	'오른쪽 귀에 1개 이상의 피어싱'	,	6	]	,
                    [	'Nose Piercing'	,	'코 피어싱'	,	7	]	,
                    [	'Chocker Necklace'	,	'초커'	,	8	]	,
                    [	'Lip Piercing'	,	'입술 피어싱'	,	9	]	,
                    [	'Eyebrow Piercing'	,	'눈썹 피어싱'	,	9	]	,
                    [	'Leg Prosthetics'	,	'의족'	,	2	]	,
                    [	'Black Disposable Mask'	,	'검정색 일회용 마스크 '	,	10	]	,
                    [	'Charm Earrings'	,	'장식이 있는 귀걸이'	,	11	]	,
                    [	'Drop earrings'	,	'아주 긴 드롭형 귀걸이'	,	12	]	,
                    [	'Millitary Backpack'	,	'군용 밀리터리 백팩'	,	25	]	,
                    [	'Wide Leather Bracelet'	,	'손목을 다 덮는 가죽 팔찌'	,	13	]	,
                    [	'Tennis Wristband'	,	'스포츠 손목 보호대'	,	14	]	,
                    [	'Colorful Bracelets'	,	'팔 위에 여러 겹 겹쳐 낀 화려한 팔찌들'	,	15	]	,
                    [	'Cross Charm Bracelet'	,	'십자가 모양의 장식이 달린 명품 팔찌'	,	17	]	,
                    [	'Lion Shaped Ring'	,	'사자 얼굴 모양으로 조각된 은색 반지'	,	18	]	,
                    [	'Silver Stainless Ring'	,	'은색 써지컬 반지 '	,	19	]	,
                    [	'Electronics Anklet'	,	'전자 발찌'	,	20	]	,
                    [	'Gold Cross Necklace'	,	'십자가 펜던트가 달린 얆은 금목걸이'	,	21	]	,
                    [	'Thick Chain Nechlace'	,	'은색 굵은 체인 목걸이'	,	22	]	,
                    [	'Black Backpack'	,	'검은색 백팩'	,	23	]	,
                    [	'Engagement Ring'	,	'네 번째 손가락 반지'	,	24	]	,
                    [	'Buddhist Bead Bracelet'	,	'불교 나무 염주 팔찌'	,	16	]	,
                    [	'Stud Earrings'	,	'귀에 딱 붙는 귀걸이'	,	27	]	
     ],

     'JOB' : [
                [	'Librarian'	,	'도서관 사서'	,	1	]	,
                [	'Carpenter'	,	'목수'	,	2	]	,
                [	'Homeless'	,	'노숙자'	,	3	]	,
                [	'Police Officer'	,	'경찰'	,	4	]   ,
                [	'Photographer'	,	'포토그래퍼'	,	5	]	,
                [	'Lawyer'	,	'변호사'	,	6	]	,
                [	'Doctor'	,	'의사'	,	7	]	,
                [	'Athlete'	,	'운동선수'	,	8	]	,
                [	'Hair Designer'	,	'미용사'	,	9	]	,
                [	'Banker'	,	'은행원'	,	10	]	,
                [	'Actor'	,	'배우'	,	11	]	,
                [	'Director'	,	'연출가'	,	12	]	,
                [	'Model'	,	'모델'	,	13	]	,
                [	'Firefighter'	,	'소방관'	,	14	]	,
                [	'Professor'	,	'교수'	,	15	]	,
                [	'Mechanic'	,	'정비공'	,	16	]	,
                [	'Receptionist'	,	'접수원'	,	17	]	,
                [	'Cleaner'	,	'청소부'	,	18	]	,
                [	'Athletic Trainer'	,	'스포츠 트레이너'	,	19	]	,
                [	'Security Guard'	,	'보안 요원'	,	20	]	,
                [	'Janitor'	,	'경비원'	,	21	]	,
                [	'Guard'	,	'경호원'	,	22	]	,
                [	'Chef'	,	'요리사'	,	23	]	,
                [	'Engineer'	,	'연구원'	,	24	]	,
                [	'Soldier'	,	'군인'	,	25	]	,
                [	'Sanitation Worker'	,	'환경미화원'	,	26	]	,
                [	'Nurse'	,	'간호사'	,	27	]	,
                [	'Mart Cashier'	,	'마트 직원'	,	28	]	,
                [	'Hiker'	,	'등산객 '	,	29	]                 
    ],


    'RECORDED TIME' :        [ 
                    [	'Around Midnight'	,	'밤 12시'	,	0.5	]	,
                    [	'Late Afternoon'	,	'오후 3시'	,	2	]	,
                    [	'Early Morning'	,	'오전 6시'	,	3	]	,
                    [	'Deep Dawn'	,	'오전 3시'	,	4	]	,
                    [	'Night'	,	'오후 6시'	,	5	]	,
                    [	'Morning'	,	'오전 9시'	,	6	]	,
                    [	'Late Night'	,	'오후 9시'	,	7	]
    ],

    'RECORDED PLACE' :       [
                    [	'Old Snack Bar'	,	'학교 앞 30년은 되어 보이는 분식집'	,	1	]	,
                    [	'Exquisite Pool Villa'	,	'부촌에 위치한 고급 빌라 '	,	2	]	,
                    [	'7 Star Hotel'	,	'도심에 위치한 7성급 고급 호텔'	,	3	]	,
                    [	'Rooftop Café'	,	'건물 한 채를 차지한 카페의 루프탑'	,	4	]	,
                    [	'Meat Cold Storage'	,	'도축된 가축들을 보관하는 냉동창고'	,	5	]	,
                    [	'Small Theater Backstage'	,	'대학로의 실내 소극장 무대 뒤'	,	6	]	,
                    [	'Fire Escape Building '	,	'대기업 건물 32층 비상계단'	,	7	]	,
                    [	'Big Square Backstage'	,	'넓은 광장에 설치된 야외 무대 뒤'	,	8	]	,
                    [	'Large Department Sotre'	,	'최근 리모델링을 마친 넓고 복잡한 구조의 백화점'	,	9	]	,
                    [	'Officetel Elevator'	,	'오피스텔의 5층 엘리베이터'	,	10	]	,
                    [	'Officetel  '	,	'오피스텔 안'	,	11	]	,
                    [	'Officetel Staircase'	,	'오피스텔의 12층 계단실'	,	12	]	,
                    [	'Underground Parking Lot'	,	'조명이 켜진 아파트 건설 현장의 지하 주차장'	,	13	]	,
                    [	'Custom Camping Car'	,	'H사의 커스텀 캠핑카'	,	14	]	,
                    [	'Normal House'	,	'이웃 주택과 거리가 먼 개인 주택'	,	15	]	,
                    [	'Franchise Pub'	,	'2층에 있는 프랜차이즈 술집'	,	16	]	,
                    [	'School Reunions'	,	'지하 술집에서 열린, 예약된 사람들만 참여할 수 있는 동창회'	,	17	]	,
                    [	'Party Room'	,	'새로 건축된 깔끔한 파티룸'	,	18	]	,
                    [	'Luxury Club'	,	'간판 없는, 고층에 위치한 회원제 클럽'	,	19	]	,
                    [	'Small Café'	,	'골목길 작은 개인 카페'	,	20	]	,
                    [	'5 Star hotel'	,	'깔끔하고 직원 수가 적은 5성급 비즈니스 호텔'	,	21	]	,
                    [	'Airbnb With Host'	,	'호스트와 함께 거주하는 개인주택 에어비앤비'	,	22	]	,
                    [	'Studio Airbnb '	,	'혼자 거주할 수 있는 원룸형 에어비앤비'	,	23	]	,
                    [	'Hostel (Mixed Dorm)'	,	'세계 각국의 여행자가 머무르는 혼성 호스텔'	,	24	]	,
                    [	'Hostel (Normal Dorm)'	,	'세계 각국의 여행자가 머무르는 호스텔'	,	25	]	,
                    [	'Old Guest House'	,	'계곡가에 위치한, 노인이 운영하는 민박'	,	26	]	,
                    [	'New Guest House '	,	'바닷가에 위치한, 청년들이 운영하는 게스트 하우스'	,	27	]	,
                    [	'Greek Style Pension'	,	'바닷가에 위치한 그리스식 인테리어 펜션'	,	28	]	,
                    [	'Subway Station Entrance'	,	'유동인구가 많은 지하철 역 입구'	,	29	]	,
                    [	'Convinience Store Table'	,	'아파트 근처 편의점 앞 테이블'	,	30	]	,
                    [	'Café Terrace'	,	'1층 프랜차이즈 카페의 테라스'	,	31	]	,
                    [	'Passenger Seat'	,	'특색 없는 일반 자동차의 조수석'	,	32	]	,
                    [	'Back Seats'	,	'특색 없는 일반 자동차의 뒷좌석'	,	33	]	,
                    [	'Cargo Truck Back'	,	'H사 포터 트럭의 짐칸'	,	34	]	,
                    [	'SUV Passenger Seat'	,	'검은색 SUV 차량 앞좌석'	,	35	]	,
                    [	'Inside Camping Car'	,	'커스텀 캠핑카 안 '	,	36	]	,
                    [	'Dark Lightless Alley'	,	'가로등이 고장나 어두운 골목길'	,	37	]	,
                    [	'Closed Factory'	,	'20년 전 문을 닫은 폐공장'	,	38	]	,
                    [	'Ecological Park'	,	'사람들이 많이 오가는 저수지 옆 생태 공원'	,	39	]	,
                    [	'Sashimi Restaurant'	,	'맛집으로 소문난 유명한 동네 작은 횟집'	,	40	]	,
                    [	'Middle School'	,	'지역 학군에서 가장 유명한 중학교'	,	41	]	,
                    [	'Room Café'	,	'대학교 앞에 위치한 룸카페 '	,	42	]	,
                    [	'Dormitory High School'	,	'기숙사가 있는 자율형 사립고등학교'	,	43	]	,
                    [	'Lecture Hall'	,	'대학교 건물 안 강의실'	,	44	]	,
                    [	'Town Hall'	,	'시골 마을의 마을 회관'	,	45	]	,
                    [	'Small Theater Onstage'	,	'대학로의 실내 소극장 무대 위'	,	46	]	,
                    [	'Office '	,	'중소 기업 건물의 7층 사무실'	,	47	]	,
                    [	'Officetel Management Office '	,	'오피스텔 관리실 '	,	48	]	,
                    [	'Officetel Underground Parkinglot'	,	'오피스텔의 지하 주차장'	,	49	]	,
                    [	'Members Only Studyroom '	,	'학원가 건물 7층의 회원제 독서실'	,	50	]	,
                    [	'Private English Academy'	,	'학원가 건물 5층의 영어 학원'	,	51	]	,
                    [	'PC cafe'	,	'중학교 앞 건물 2층의 최신식 PC방'	,	52	]	,
                    [	'Gym'	,	'새로 오픈하여 회원이 별로 없는 헬스장'	,	53	]	,
                    [	'University Hospital'	,	'역 주변에 위치한 대형 대학병원'	,	54	]	,
                    [	'Major Bank '	,	'번화가에 위치한 대형 은행'	,	55	]	,
                    [	'House With Yard'	,	'대문과 낮은 울타리가 있는 개인주택 마당'	,	56	]	,
                    [	'Amusement Park Pillar'	,	'사람으로 늘 붐비는 실내 놀이공원의 기둥 앞'	,	57	]	,
                    [	'Big Square Onstage'	,	'넓은 광장에 설치된 야외 무대 위'	,	58	]	,
                    [	'Female Outfit Outlet'	,	'아울렛 몰의 3층 여성복 코너'	,	59	]	,
                    [	'Underground Grocery Store'	,	'프랜차이즈 대형 마트 지하 1층 식품 코너'	,	60	]	,
                    [	'Famous Traditional Market'	,	'지방의 유명 여행지로 유명한 재래 시장'	,	61	]	,
                    [	'Single Corridor Apartment'	,	'오래된 복도식 아파트'	,	62	]	,
                    [	'Karaoke Underground'	,	'지하 1층의 노래방'	,	63	]	,
                    [	'Messy Dumpster Alley'	,	'원룸촌의 더러운 분리수거장'	,	87	]	,
                    [	'Pocha '	,	'역 앞의 포장마차'	,	64	]	,
                    [	'Messy Club '	,	'사람이 너무 많은 지저분한 클럽 '	,	65	]	,
                    [	'Old DVD room '	,	'오래된 건물 3층에 있는 DVD방'	,	66	]	,
                    [	'Self Service Bar'	,	'눈에 띄는 입구가 없어 찾기 힘든 무인 주점'	,	67	]	,
                    [	'Self Service Café'	,	'오래된 공장을 개조해 만든 무인 카페'	,	68	]	,
                    [	'Motel in Downtown'	,	'번화가에 위치한 빌딩 7층의 모텔'	,	69	]	,
                    [	'Inn Near Brothel'	,	'홍등가 한복판에 위치한 오래된 여관'	,	70	]	,
                    [	'SUV Back Seats'	,	'검은색 SUV 차량 뒷좌석'	,	71	]	,
                    [	'Closed Amusement Park'	,	'넓은 공원의 폐장된 유원지'	,	72	]	,
                    [	'Deep Forest '	,	'길을 찾을 수 없는 깊은 숲 속'	,	73	]	,
                    [	'Dumpster '	,	'전국의 쓰레기들을 처리하는 쓰레기장'	,	74	]	,
                    [	'Haunted House'	,	'귀신들렸다고 소문난 버려진 폐가'	,	75	]	,
                    [	'Shared Office Toilet'	,	'공유 오피스 건물 10층 복도 화장실'	,	76	]	,
                    [	'Big Old Arboretum'	,	'개원한 지 30년 된 오래되고 넓은 수목원'	,	77	]	,
                    [	'Small Old Supermarket'	,	'동네의 작고 오래된 슈퍼마켓'	,	78	]	,
                    [	'Blackout Parking Lot'	,	'정전된 아파트 지하주차장'	,	79	]	,
                    [	'Messy Goshiwon'	,	'관리가 되지 않아 더러운 고시원'	,	80	]	,
                    [	'Old Studio Apartment'	,	'원룸촌에 위치한 오래된 원룸'	,	81	]	,
                    [	'Semi Basement Apartment'	,	'쇠창살 달린 창문이 있는 반지하 원룸'	,	82	]	,
                    [	'Motel in Backstreet'	,	'모텔촌에 위치한 오래된 모텔 '	,	83	]	,
                    [	'Lonesome Bus Station '	,	'인적 드문 시골의 유일한 버스 정류장'	,	84	]	,
                    [	'Inside Taxi'	,	'택시 안'	,	85	]	,
                    [	'Night Mountain'	,	'야산 깊은 곳'	,	86	]	,

    ],

    'RECORDED SOUND' :       [
                    [	'Toilet Flush Sound'	,	'변기 물 내리는 소리 '	,	1	]	,
                    [	'Draw With Knife'	,	'날붙이가 벽에 그어지는 소리'	,	2	]	,
                    [	'Metal Weapon Falling'	,	'철제 둔기가 떨어지는 소리'	,	3	]	,
                    [	'Dishwasher Sound'	,	'식기 세척기 소리'	,	4	]	,
                    [	'Stepping Cobble'	,	'자갈 밟는 소리 '	,	5	]	,
                    [	'Thermometer Noise'	,	'체온계 온도 체크하는 소리 '	,	6	]	,
                    [	'Beat Against Wall'	,	'벽에 부딪히는 소리'	,	7	]	,
                    [	'Breaking Bone'	,	'뼈가 부서지는 소리'	,	8	]	,
                    [	'Joint twisted'	,	'관절이 뒤틀리는 소리'	,	9	]	,
                    [	'Chalkboard Scraping'	,	'칠판을 손톱으로 긁는 소리'	,	10	]	,
                    [	'Wooden Weapon Falling'	,	'목재 둔기가 떨어지는 소리'	,	11	]	,
                    [	'Sound of Chainsaw'	,	'전기톱 소리 '	,	12	]	,
                    [	'Drilling'	,	'드릴 소리'	,	13	]	,
                    [	'Grind one`s Teeth'	,	'이를 가는 소리'	,	14	]	,
                    [	'Screaming'	,	'비명 소리'	,	15	]	,
                    [	'Strong Wind'	,	'거센 바람 소리'	,	16	]	,
                    [	'Throw Up Blood'	,	'피 토하는 소리 '	,	17	]	,
                    [	'Draw On Asphalt'	,	'사물이 아스팔트 바닥에 끌리는 소리'	,	18	]	,
                    [	'Electric Fan Sound'	,	'선풍기 소리'	,	19	]	,
                    [	'Counting Money'	,	'돈 세는 소리'	,	20	]	,
                    [	'Washing Machine Sound'	,	'세탁기 소리'	,	21	]	,
                    [	'Pipe Hitting Wall'	,	'파이프를 벽에 부딪치는 소리'	,	22	]	,
                    [	'Birds Singing'	,	'새 우는 소리'	,	23	]	,
                    [	'Backpack Stuff Shaking'	,	'가방 안 물건들이 흔들리는 소리'	,	24	]	,
                    [	'Water Shaking'	,	'물병 안의 물이 흔들리는 소리'	,	25	]	,
                    [	'Plastic Beating Sound'	,	'플라스틱이 서로 부딪치는 소리'	,	26	]	,
                    [	'Keyboard Sound'	,	'키보드 소리'	,	27	]	,
                    [	'Computer Mouse Clicking'	,	'마우스 클릭 소리'	,	28	]	,
                    [	'Slip and Crash'	,	'사물이 미끄러져 박살나는 소리 '	,	29	]	,
                    [	'Chewing Gum'	,	'껌 씹는 소리 '	,	30	]	,
                    [	'Spit On Ground'	,	'바닥에 침을 뱉는 소리'	,	31	]	,
                    [	'Hazy Music '	,	'어디에선가 들려오는 희미한 음악 소리 '	,	32	]	,
                    [	'Quite Conversation'	,	'나지막한 대화 소리'	,	33	]	,
                    [	'Remote Air Conditioner'	,	'에어컨 조작 소리 '	,	34	]	,
                    [	'Grill the Meat'	,	'고기 굽는 소리 '	,	35	]	,
                    [	'Dog Barking'	,	'강아지 짖는 소리'	,	36	]	,
                    [	'Cat Meow'	,	'고양이 우는 소리'	,	37	]	,
                    [	'Reading Buddhist Text'	,	'불경 읊는 소리'	,	38	]	,
                    [	'Singing Gospell'	,	'찬송가 부르는 소리 '	,	39	]	,
                    [	'Running Treadmill'	,	'런닝머신 돌아가는 소리 '	,	40	]	,
                    [	'Sand Stepping Barefoot'	,	'맨발로 모래 밟는 소리 '	,	41	]	,
                    [	'Sound of Wave'	,	'파도 소리 '	,	42	]	,
                    [	'Water Flowing Sound'	,	'물이 흐르는 소리 '	,	43	]	,
                    [	'Gas Range On'	,	'가스레인지를 켜는 소리 '	,	44	]	,
                    [	'Cutlery Falling down'	,	'날붙이가 떨어지는 소리 '	,	45	]	,
                    [	'Cutting Something '	,	'무언가를 자르는 소리'	,	46	]	,
                    [	'Irregular Walking Sound '	,	'불규칙한 발걸음 소리'	,	47	]	,
                    [	'Skid Sounds'	,	'자동차 브레이크 소리'	,	48	]	,
                    [	'Bearing Groaning'	,	'신음 참는 소리'	,	49	]	,
                    [	'Neon Sign Noise'	,	'네온사인 간판 소리 '	,	50	]	,
                    [	'Whistle'	,	'휘파람 소리'	,	51	]	,
                    [	'Phone Alarm Ringing'	,	'핸드폰 알람 소리 '	,	52	]	,
                    [	'Fan Sound'	,	'부채 소리'	,	53	]	,
                    [	'Finger Snap'	,	'손가락 튕기는 소리'	,	54	]	,
                    [	'Cars On Highway'	,	'고속도로 자동차 소리'	,	55	]	,
                    [	'Digging With Shovel'	,	'삽으로 흙을 파는 소리 '	,	56	]	,
                    [	'Hammering Sound '	,	'망치질 소리 '	,	57	]	,
                    [	'People Having Conversation'	,	'사람들의 대화 소리'	,	58	]	,
                    [	'Twisting Jaw joint'	,	'턱 관절이 어긋나는 소리'	,	59	]	,
                    [	'Crack Knuckles'	,	'손 관절을 꺾는 소리'	,	60	]	,
                    [	'Propeller Sound'	,	'헬리콥터 프로펠러 소리'	,	61	]	,
                    [	'Chewing Paper Cup'	,	'종이컵을 잘근잘근 씹는 소리'	,	62	]	,
                    [	'TV Sports Commentaries'	,	'TV 속 스포츠 방송 중계 소리 '	,	63	]
    ],

    'TRACE' :       [
                    [	'Weapon Without Fingerprint'	,	'지문이 없는 흉기'	,	1	]	,
                    [	'Black Wig Hair'	,	'검정색 머리카락 (인조모)'	,	2	]	,
                    [	'Well Preserved Crimescene'	,	'금품이 보존된, 잘 정돈된 현장'	,	3	]	,
                    [	'Note By Suspect'	,	'범인이 남긴 쪽지 '	,	4	]	,
                    [	'Puppa Maggot'	,	'번데기 상태의 구더기'	,	5	]	,
                    [	'Solid Blood'	,	'완전히 응고된 혈액'	,	6	]	,
                    [	'Not Solidfied Blood'	,	'완전히 응고되지 않은 혈액'	,	7	]	,
                    [	'Erased Blood Stain'	,	'루미놀 검사로 발견된 지워진 혈액 자국'	,	8	]	,
                    [	'Bloodstained Everywhere'	,	'혈액이 튄 벽지와 바닥'	,	9	]	,
                    [	'Footprint 265mm workshoes'	,	'사이즈 265mm의 작업화 족적'	,	10	]	,
                    [	'Footprint 270mm Sneakers'	,	'사이즈 270mm의 운동화 족적 '	,	11	]	,
                    [	'Footprint 240mm Loper'	,	'사이즈 240mm의 단화 족적'	,	12	]	,
                    [	'Footprint 245mm Highheels'	,	'사이즈 245mm의 하이힐 족적'	,	13	]	,
                    [	'Black Button'	,	'검정색 단추'	,	14	]	,
                    [	'Different Soil'	,	'사건 현장 주변 토양과 다른 성분의 흙'	,	15	]	,
                    [	'Ripped Cloth'	,	'찢어진 옷소매'	,	16	]	,
                    [	'Lipstick Without Fingerprint'	,	'지문이 묻어 있지 않는 립스틱'	,	17	]	,
                    [	'Messed Up Crimescene'	,	'금품이 사라진, 마구 어질러진 현장'	,	18	]	,
                    [	'Cigarette Butts'	,	'필터만 남은 담배꽁초 '	,	19	]	,
                    [	'Crumpled Cigarette Package'	,	'구겨진 담배갑'	,	20	]	,
                    [	'Empty Cartridge'	,	'탄피'	,	21	]	,
                    [	'Black Powder'	,	'화약 가루'	,	22	]	,
                    [	'Body Hair'	,	'체모'	,	23	]	,
                    [	'Black Vinyl Bag'	,	'검은 비닐 봉지 '	,	24	]	,
                    [	'Headlight'	,	'헤드 라이트'	,	25	]	,
                    [	'Metal Fragments'	,	'금속 파편'	,	26	]	,
                    [	'Glass Fragments'	,	'유리 파편'	,	27	]	,
                    [	'Skid Mark '	,	'타이어 자국'	,	28	]	,
                    [	'Scorch Mark'	,	'불에 그슬린 자국'	,	29	]	,
                    [	'Paint Stain'	,	'페인트 자국'	,	30	]	,
                    [	'Feather'	,	'옷 충전재로 사용되는 깃털 몇 가닥'	,	31	]	,
                    [	'Irregular Footprints'	,	'불규칙하게 찍힌 족적'	,	32	]	,
                    [	'Written In Blood'	,	'핏자국으로 그린 표식'	,	33	]	,
                    [	'Tape Recorded Voice '	,	'범인의 목소리가 담긴 녹음 테이프'	,	34	]	,
                    [	'Arson Attempt'	,	'방화 시도의 흔적'	,	35	]	,
                    [	'Disposable Lighter'	,	'음식점 전화번호가 쓰여 있는 일회용 라이터'	,	36	]	,
                    [	'Flies '	,	'현장에 날아다니는 파리'	,	37	]	,
                    [	'Maggot'	,	'이제 막 태어난 작은 구더기 '	,	38	]	,
                    [	'Light Brown Hair'	,	'밝은 갈색의 머리카락'	,	39	]	,
                    [	'Nail Tip'	,	'떨어진 네일팁'	,	40	]	,
                    [	'Excrements'	,	'배설물'	,	41	]	,
                    [	'Suspect`s Toilet Paper'	,	'범인이 사용한 휴지 '	,	42	]	,
                    [	'Lipstick Stained Cigarette'	,	'립스틱이 묻은 담배꽁초'	,	43	]	,
                    [	'Handprint On Arm'	,	'피해자의 팔에 남은 손자국'	,	44	]	,
                    [	'Bullet In Body'	,	'부검 후 발견된 총알 '	,	45	]	,
                    [	'Fibrous Tissue'	,	'섬유 조직'	,	46	]	,
                    [	'Vanished Underwear'	,	'사라진 속옷'	,	47	]	,
                    [	'Fingerprint'	,	'지문 '	,	48	]	,
                    [	'Black Hair'	,	'검정색 머리카락'	,	49	]	,
                    [	'Suspect`s Tissue '	,	'피해자 손톱 밑 피부 조직'	,	50	]	,
                    [	'Weapon With Fingerprint'	,	'지문이 있는 흉기'	,	51	]	,
                    [	'Chewed Gum'	,	'구겨진 은박지에 싸인 씹던 껌'	,	52	]	,
    ]
}
